from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
import joblib


train_ex = [
    # plumbing:
    ("pipe leark under sink", "Plumbing"),
    ("toilet clogged", "Plumbing"),
    ("water heater not working", "Plumbing"),
    ("water leaking from ceiling", "Plumbing"),
    ("faucet dripping", "Plumbing"),
    ("shower head broken", "Plumbing"),
    ("garbage disposal jammed", "Plumbing"),
    ("sewer line backup", "Plumbing"),
    ("water pressure low", "Plumbing"),
    ("drain is backed up", "Plumbing"),
    ("need plumber for pipe installation", "Plumbing"),
    ("leaking pipe in basement", "Plumbing"),
    ("clogged sink drain", "Plumbing"),
    ("need help with water heater", "Plumbing"),
    ("toilet is overflowing", "Plumbing"),
    ("water damage from burst pipe", "Plumbing"),
    ("need plumber for bathroom remodel", "Plumbing"),
    ("leaking faucet in kitchen", "Plumbing"),
    ("shower drain is clogged", "Plumbing"),
    ("need plumber for water line repair", "Plumbing"),
    ("fuga de agua debajo del fregadero", "Plumbing"),
    ("inodoro atascado", "Plumbing"),
    ("calentador de agua no funciona", "Plumbing"),
    ("agua goteando del techo", "Plumbing"),
    ("grifo goteando", "Plumbing"),
    ("cabezal de ducha roto", "Plumbing"),
    ("triturador de basura atascado", "Plumbing"),
    ("respaldo de la línea de alcantarillado", "Plumbing"),
    ("presión de agua baja", "Plumbing"),
    ("el desagüe está respaldado", "Plumbing"),
    ("necesito plomero para instalación de tubería", "Plumbing"),
    ("tubería con fuga en el sótano", "Plumbing"),
    ("desagüe del fregadero atascado", "Plumbing"),
    ("necesito ayuda con el calentador de agua", "Plumbing"),
    ("el inodoro se está desbordando", "Plumbing"),
    ("daño por agua debido a tubería rota", "Plumbing"),
    ("necesito plomero para remodelación de baño", "Plumbing"),
    ("grifo con fuga en la cocina", "Plumbing"),
    ("el desagüe de la ducha está atascado", "Plumbing"),
    ("necesito plomero para reparación de la línea de agua", "Plumbing"),

    # electrical:
    ("light fixture not working", "Electrical"),
    ("power outage in part of house", "Electrical"),
    ("outlet sparks when used", "Electrical"),
    ("circuit breaker keeps tripping", "Electrical"),
    ("need electrician for wiring issue", "Electrical"),
    ("ceiling fan not working", "Electrical"),
    ("electrical panel upgrade needed", "Electrical"),
    ("smoke detector beeping", "Electrical"),
    ("need help with electrical code compliance", "Electrical"),
    ("exposed wires in basement", "Electrical"),
    ("light switch not working", "Electrical"),
    ("need electrician for home renovation project", "Electrical"),
    ("electrical outlet not working", "Electrical"),
    ("need help with electrical safety inspection", "Electrical"),
    ("circuit breaker is hot to touch", "Electrical"),
    ("need electrician for outdoor lighting installation", "Electrical"),
    ("electrical shock when touching outlet", "Electrical"),
    ("need help with electrical grounding issue", "Electrical"),
    ("light fixture is flickering", "Electrical"),
    ("lámpara no funciona", "Electrical"),
    ("corte de energía en parte de la casa", "Electrical"),
    ("el enchufe hace chispas al usarse", "Electrical"),
    ("el interruptor automático sigue disparándose", "Electrical"),
    ("necesito electricista para problema de cableado", "Electrical"),
    ("el ventilador de techo no funciona", "Electrical"),
    ("actualización del panel eléctrico necesaria", "Electrical"),
    ("el detector de humo está pitando", "Electrical"),
    ("necesito ayuda con el cumplimiento del código eléctrico", "Electrical"),
    ("cables expuestos en el sótano", "Electrical"),
    ("el interruptor de luz no funciona", "Electrical"),
    ("necesito electricista para proyecto de renovación del hogar", "Electrical"),
    ("el enchufe eléctrico no funciona", "Electrical"),
    ("necesito ayuda con la inspección de seguridad eléctrica", "Electrical"),
    ("el interruptor automático está caliente al tacto", "Electrical"),
    ("necesito electricista para instalación de iluminación exterior", "Electrical"),
    ("choque eléctrico al tocar el enchufe", "Electrical"),
    ("necesito ayuda con problema de conexión a tierra eléctrica", "Electrical"),
    ("la lámpara parpadea", "Electrical"),

    # HVAC:
    ("air conditioner not cooling", "HVAC"),
    ("heater not working", "HVAC"),
    ("need help with thermostat programming", "HVAC"),
    ("furnace making strange noises", "HVAC"),
    ("air filter replacement needed", "HVAC"),
    ("ductwork repair needed", "HVAC"),
    ("need HVAC technician for maintenance", "HVAC"),
    ("refrigerant leak in AC unit", "HVAC"),
    ("need help with energy efficiency improvements", "HVAC"),
    ("humidifier not working properly", "HVAC"),
    ("air conditioner is leaking water", "HVAC"),
    ("need HVAC technician for installation of new system", "HVAC"),
    ("furnace is not igniting", "HVAC"),
    ("need help with zoning system setup", "HVAC"),
    ("air conditioner is freezing up", "HVAC"),
    ("need HVAC technician for duct cleaning", "HVAC"),
    ("heat pump not working", "HVAC"),
    ("need help with indoor air quality issues", "HVAC"),
    ("air conditioner is making loud noises", "HVAC"),
    ("el aire acondicionado no enfría", "HVAC"),
    ("la calefacción no funciona", "HVAC"),
    ("necesito ayuda con la programación del termostato", "HVAC"),
    ("el horno hace ruidos extraños", "HVAC"),   
    ("reemplazo de filtro de aire necesario", "HVAC"),
    ("reparación de conductos necesaria", "HVAC"),
    ("necesito técnico de HVAC para mantenimiento", "HVAC"),
    ("fuga de refrigerante en la unidad de aire acondicionado", "HVAC"),
    ("necesito ayuda con mejoras de eficiencia energética", "HVAC"),
    ("el humidificador no funciona correctamente", "HVAC"),
    ("el aire acondicionado está goteando agua", "HVAC"),
    ("necesito técnico de HVAC para instalación de nuevo sistema", "HVAC"),
    ("el horno no se enciende", "HVAC"),
    ("necesito ayuda con la configuración del sistema de zonificación", "HVAC"),
    ("el aire acondicionado se está congelando", "HVAC"),
    ("necesito técnico de HVAC para limpieza de conductos", "HVAC"),
    ("la bomba de calor no funciona", "HVAC"),
    ("necesito ayuda con problemas de calidad del aire interior", "HVAC"),
    ("el aire acondicionado hace ruidos fuertes", "HVAC"),

    # general:
    ("need help with home improvement project", "General"),
    ("looking for handyman services", "General"),
    ("need help with furniture assembly", "General"),
    ("home maintenance tasks needed", "General"),
    ("need help with yard work or landscaping", "General"),
    ("looking for general contractor for home renovation", "General"),
    ("need help with moving or hauling", "General"),
    ("looking for cleaning services for home", "General"),
    ("need help with pest control in home", "General"),
    ("looking for interior design services", "General"),
    ("need help with home organization or decluttering", "General"),
    ("looking for painting services for home", "General"),
    ("need help with flooring installation or repair", "General"),
    ("looking for roofing services for home", "General"),
    ("need help with window installation or repair", "General"),
    ("looking for siding services for home", "General"),
    ("need help with deck or patio construction or repair", "General"),
    ("looking for fencing services for home", "General"),
    ("need help with garage door installation or repair", "General"),
    ("looking for general handyman services in Spanish", "General"),
    ("necesito ayuda con un proyecto de mejora del hogar", "General"),
    ("buscando servicios de manitas", "General"),
    ("necesito ayuda con el montaje de muebles", "General"),
    ("se necesitan tareas de mantenimiento del hogar", "General"),
    ("necesito ayuda con el trabajo de jardín o paisajismo", "General"),
    ("buscando contratista general para renovación del hogar", "General"),
    ("necesito ayuda con mudanza o transporte", "General"),
    ("buscando servicios de limpieza para el hogar", "General"),
    ("necesito ayuda con el control de plagas en el hogar", "General"),
    ("buscando servicios de diseño de interiores", "General"),
    ("necesito ayuda con la organización del hogar o el desorden", "General"),
    ("buscando servicios de pintura para el hogar", "General"),
    ("necesito ayuda con instalación o reparación de pisos", "General"),
    ("buscando servicios de techado para el hogar", "General"),
    ("necesito ayuda con instalación o reparación de ventanas", "General"),
    ("buscando servicios de revestimiento para el hogar", "General"),
    ("necesito ayuda con construcción o reparación de terraza o patio", "General"),
    ("buscando servicios de cercado para el hogar", "General"),
    ("necesito ayuda con instalación o reparación de puerta de garaje", "General"),
    ("buscando servicios generales de manitas en español", "General"),
]

txts = [x[0] for x in train_ex]
labels = [x[1] for x in train_ex]

model = Pipeline([
    ("tfidf", TfidfVectorizer(ngram_range=(1, 2))),
    ("clf", LogisticRegression(max_iter=1000, verbose=True))
    ])

model.fit(txts, labels)

joblib.dump(model, "service_classifier.joblib")
print("Model trained and saved as service_classifier.joblib")

data = joblib.load("service_classifier.joblib")
print(data)